version: '3'

services:

  backend:
    container_name: backend
    restart: always
    build: ./backend
    volumes: ['./backend:/backend']
    networks:
      - apinetwork
    expose:
      - "5000"
    ports:
      - "5000:5000"
    env_file:
    - .env

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - apinetwork
    expose:
      - "8080"
    ports:
      - "80:8080"

networks:
  apinetwork: