version: '3'

services:


  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    build: ./nginx
    networks:
      - apinetwork
    expose:
      - "8080"
    ports:
      - "80:8080"
      - "443:8080"

  backend:
    container_name: backend
    depends_on:
            - nginx-proxy
    restart: always
    build: ./backend
    volumes: ['./backend:/backend']
    networks:
      - apinetwork

    ports:
      - "5000:5000"
    env_file:
    - .env

  redis:
    container_name: redis
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - apinetwork


  frontend:
    container_name: frontend
    depends_on:
        - nginx-proxy
    build: ./frontend
    restart: always
    volumes: ['./frontend:/frontend']

    networks:
      - apinetwork
    ports:
      - "8000:8000"
    env_file:
    - .env


networks:
  apinetwork: